### ISSUE TITLE
Update peer dependency version to allow Formik 2.0

### ISSUE THREAD

**Issue by R4DIC4L** [bamlab/react-native-formik#137]
Can the peer dependency be updated to also include formik version 2 or does it only work with version 1?

```
+-- UNMET PEER DEPENDENCY formik@2.1.3

npm ERR! peer dep missing: formik@>= 0.11.x < 2, required by react-native-formik@1.7.7
```

**Comment by alkalox** [comment]
I think work on react-native-formik stopped around the time the last stable version of Formik 1.x.x came out, which was 1.5.8, the package hasn't been updated for Formik v2.x.x

Right now it's working with Formik@1.5.8, for any future people who wish to use this package.

**Comment by IzliaB** [comment]
Hi! You can resolve that? I have same problem, I updated react native from 0.59 to recent version, and when I want to run the project, I get these errors. Could anyone help me, please? Please please please

**Comment by alkalox** [comment]
@IzliaB Look at this comment, you need to provide the initialValues prop in Formik component https://github.com/bamlab/react-native-formik/issues/142#issuecomment-712881476 or this comment https://github.com/bamlab/react-native-formik/issues/173#issuecomment-968303052
