### ISSUE TITLE
react-native-formik throws an error and doesn't work AT ALL with Formik v2

### ISSUE THREAD

**Issue by alkalox** [bamlab/react-native-formik#146]
This error comes when typing into any text field -
 `TypeError: undefined is not an object (evaluating '(i === 0 ? obj : resVal)[pathArray[i]]')`

This error occurs even with the example code in README.

It seems like work on react-native-formik stopped around the time the last stable version of Formik 1.x.x came out, which was 1.5.8, the package has not been updated for Formik v2

Right now it's working with **Formik@1.5.8**, for anyone who wishes to use this package.

**Comment by bramski** [comment]
Is there a planned fix? Formik v2 is out for nearly a year now.

**Comment by bramski** [comment]
@Almouro ? Is this library deprecated?

**Comment by elcssmouhsine** [comment]
it seems there is no active development on this repo, did anyone made a fork for it to work with v2 ?

**Comment by Ripplz** [comment]
@alkalox @bramski @elcssmouhsine I use this library with Formik v2.1.5 on my React Native app (Expo), and it works just fine.

From the error message, I think this has to do with an upgrade made in Formik v2^, which requires you to provide a value for each of your form elements in an object passed to your Formik component's `initialValues` prop.

Try this and see if it would work.

**Comment by Ripplz** [comment]
Okay, I've successfully reproduced this error in my Formik v2+ app, and I can confirm it's what I mentioned above. You don't need to downgrade your Formik, just include the `initalValues` prop on your `<Formik>` component

**Comment by alkalox** [comment]
@Ripplz Yes, you're right, that was what was missing. Thanks!
