### ISSUE TITLE
Import DatePicker from `react-native-form-idable`

### ISSUE THREAD

**Issue by Almouro** [bamlab/react-native-formik#18]
Picker in [here](https://github.com/bamlab/react-native-form-idable) was quite good with a native feel and a clean API for both Android & iOS
We should import it in the same way we did with `Picker`

**Comment by daviscabral** [comment]
I am using the `react-native-modal-datetime-picker` component. Connected it with `react-native-formik` and used an `Input` from `react-native-elements`. Seems pretty good so far - using both native elements from each platform.

**Comment by Almouro** [comment]
Closed, indeed `react-native-modal-datetime-picker` works well :)
