### ISSUE TITLE
How to add initialValues?

### ISSUE THREAD

**Issue by ikhsanalatsary** [bamlab/react-native-formik#27]
Hi, I'm really excited about this package. The initialValues won't work with this lib. So, How to add initialValues?

**Comment by Tketa** [comment]
Hi @ikhsanalatsary 

The injection of initial values is handled by Formik, not by this library.

- If you use `<Formik />`: https://github.com/jaredpalmer/formik#initialvalues-values
- If you use the `withFormik` higher-order component: https://github.com/jaredpalmer/formik#mappropstovalues-props-props--values

Let me know if that makes sense

**Comment by ikhsanalatsary** [comment]
ya, but the problem I faced is different. The initialValues won't work with this lib caused [this code](https://github.com/bamlab/react-native-formik/blob/da1108d47c23f4c08de7da14a07e99ab7508476c/src/setFormikInitialValue.js#L12) and [this test](https://github.com/bamlab/react-native-formik/blob/da1108d47c23f4c08de7da14a07e99ab7508476c/src/__tests__/setFormikInitialValue.js#L39). So, I copied it and changed it as my own HOC and then compose it.

```js
import React from 'react'
import { withFormik } from 'react-native-formik'
import has from 'lodash/has'
import compose from 'recompose/compose'

const setFormikInitialValue = WrappedInput => {
  return class WithFocusProp extends React.PureComponent {
    constructor (props) {
      super(props)

      const { formik, name } = props
      if (has(formik.initialValues, name)) {
        formik.setValues({ ...formik.initialValues })
      }
    }

    render () {
      return <WrappedInput {...this.props} />
    }
  }
}

export default compose(withFormik, setFormikInitialValue)

```

and works.

**Comment by ikhsanalatsary** [comment]
I closed this issue, but if any better solution than this you can drop in the comment. thanks
