### ISSUE TITLE
unable to run sample code in expo snacks

### ISSUE THREAD

**Issue by lidiexy** [bamlab/react-native-formik#36]
Hi, good job in this package. I wonder if I missed something in my code, please check this out?
https://snack.expo.io/HkFpyjdrm

Thanks

**Comment by FadiAboMsalam** [comment]
i also couldn't run [https://github.com/bamlab/react-native-formik#Custom-components](switch example)

**Comment by Almouro** [comment]
Hi @FadiAboMsalam and @lidiexy, 
This issue was there for quite a while but it is now with the latest version! 🎉 Thanks for reporting!
See: https://snack.expo.io/@almouro/react-native-formik-gist
