### ISSUE TITLE
using checkbox

### ISSUE THREAD

**Issue by FadiAboMsalam** [bamlab/react-native-formik#40]
Hi ,
is there any way i can apply formik in react native for **checkbox** ?

i want to the checkbox to be required, any chance this is doable ? 

thanks in advance

**Comment by Almouro** [comment]
Hi @FadiAboMsalam, sorry for the very late reply! 🙏 
You can check out an example using the native React Native switch here: https://github.com/bamlab/react-native-formik#simple-example-using-a-switch.

I'm closing this, but feel free to reopen if you have any questions!

**Comment by FadiAboMsalam** [comment]
@Almouro hi again,
i just installed the  react-native-formik 
in my package.json  `   "react-native-formik": "^1.7.0",`

i tried the example but it seems there is a bug in the library and when i import `withFormikControl` it is undefinded

i tried to console.log the following 
`import * as componentLibrary from "react-native-formik";`
here is the result in 
![image](https://user-images.githubusercontent.com/12826829/50377331-215f6500-0624-11e9-9db7-2bb68811b8e7.png)

can you please check thanks :) 
and keep up the good progress in this amazing repo
